name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22"

    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Test
      run: |
        go test ./... -coverprofile=profile.cov

    - uses: shogo82148/actions-goveralls@v1.9.0
      with:
        path-to-profile: profile.cov